# Copyright (c) 2026 Samsarix LLC
# SPDX-License-Identifier: MPL-2.0

"""Generate or check the universal development/build dependency lock.

Checking is offline and needs only Python's standard library. Generation uses
the pinned uv compiler and PyPI, preserving locked versions unless --upgrade is
explicit. The project itself is installed separately from reviewed local source.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import json
import os
import re
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

LOCK_NAME = "requirements-dev.lock"
OPTIONS = [
    "--universal",
    "--generate-hashes",
    "--no-header",
    "--no-annotate",
    "--no-config",
    "--no-build",
]
INDEX = "https://pypi.org/simple"


def inputs(repository: Path) -> tuple[str, str, str, str]:
    """Return input text, fingerprint, minimum Python, and compiler version."""

    project = tomllib.loads((repository / "pyproject.toml").read_text(encoding="utf-8"))
    direct = [
        line.strip()
        for line in (repository / "requirements-dev.txt").read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]
    uv_pins = [line.removeprefix("uv==") for line in direct if line.startswith("uv==")]
    if len(uv_pins) != 1:
        raise ValueError("requirements-dev.txt must contain exactly one uv==VERSION pin")
    python_requirement = project["project"]["requires-python"]
    match = re.fullmatch(r">=(\d+\.\d+)", python_requirement)
    if match is None:
        raise ValueError("Update lock generation for this requires-python range")
    requirements = [
        *project["project"].get("dependencies", []),
        *project["build-system"]["requires"],
        *direct,
    ]
    state = {
        "requirements": requirements,
        "python": python_requirement,
        "options": OPTIONS,
        "index": INDEX,
    }
    digest = hashlib.sha256(json.dumps(state, sort_keys=True).encode("utf-8")).hexdigest()
    return "\n".join(requirements) + "\n", digest, match[1], uv_pins[0]


def render_lock(body: str, fingerprint: str) -> str:
    body = body.replace("\r\n", "\n").strip() + "\n"
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    return (
        "# Copyright (c) 2026 Samsarix LLC\n"
        "# SPDX-License-Identifier: MPL-2.0\n"
        "# Generated by: python scripts/lock_dependencies.py\n"
        "# Install with: python -m pip install --require-hashes "
        "--only-binary=:all: -r requirements-dev.lock\n"
        f"# Inputs SHA-256: {fingerprint}\n"
        f"# Lock SHA-256: {digest}\n\n{body}"
    )


def check_lock(repository: Path) -> None:
    _, expected, _, _ = inputs(repository)
    content = (repository / LOCK_NAME).read_text(encoding="utf-8")
    header, separator, body = content.partition("\n\n")
    if not separator or f"# Inputs SHA-256: {expected}" not in header.splitlines():
        raise ValueError("Dependency inputs changed; run python scripts/lock_dependencies.py")
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    if f"# Lock SHA-256: {digest}" not in header.splitlines():
        raise ValueError("Lock body changed; regenerate instead of editing hashes or pins manually")
    if not body.strip() or "--hash=sha256:" not in body:
        raise ValueError("Dependency lock must contain hashed requirements")


def generate(repository: Path, *, upgrade: bool) -> None:
    source, fingerprint, minimum_python, compiler_version = inputs(repository)
    installed = importlib.metadata.version("uv")
    if installed != compiler_version:
        raise ValueError(f"Lock generation requires uv=={compiler_version}; installed {installed}")
    target = repository / LOCK_NAME
    env = {key: value for key, value in os.environ.items() if not key.startswith(("UV_", "PIP_"))}
    env["UV_NO_MANAGED_PYTHON"] = "1"
    with tempfile.TemporaryDirectory(prefix="samsarix-lock-") as temporary:
        candidate = Path(temporary) / LOCK_NAME
        if target.exists():
            candidate.write_text(target.read_text(encoding="utf-8"), encoding="utf-8")
        command = [
            sys.executable,
            "-m",
            "uv",
            "pip",
            "compile",
            "-",
            *OPTIONS,
            "--python-version",
            minimum_python,
            "--index-url",
            INDEX,
            "--output-file",
            str(candidate),
        ]
        if upgrade:
            command.append("--upgrade")
        subprocess.run(
            command,
            input=source,
            text=True,
            cwd=repository,
            env=env,
            timeout=180,
            check=True,
            stdout=subprocess.DEVNULL,
        )
        # Commit a complete generated file only after compilation succeeds.
        content = render_lock(candidate.read_text(encoding="utf-8"), fingerprint)
        staging: Path | None = None
        try:
            with tempfile.NamedTemporaryFile(
                mode="w",
                encoding="utf-8",
                newline="\n",
                prefix=".dependency-lock-",
                suffix=".tmp",
                dir=repository,
                delete=False,
            ) as handle:
                staging = Path(handle.name)
                handle.write(content)
            staging.replace(target)
        finally:
            if staging is not None:
                staging.unlink(missing_ok=True)
    check_lock(repository)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument("--check", action="store_true", help="offline check for source/body drift")
    modes.add_argument(
        "--upgrade", action="store_true", help="deliberately refresh transitive pins"
    )
    args = parser.parse_args()
    repository = Path(__file__).resolve().parents[1]
    try:
        if args.check:
            check_lock(repository)
        else:
            generate(repository, upgrade=args.upgrade)
    except (
        OSError,
        ValueError,
        importlib.metadata.PackageNotFoundError,
        subprocess.SubprocessError,
    ) as exc:
        print(f"Dependency lock error: {exc}", file=sys.stderr)
        return 1
    print("Dependency lock matches its inputs and recorded content.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
